### ISSUE TITLE
Change Email

### ISSUE THREAD

**Issue by yuukiconan** [KIPASGTS/Brainly-Scrambler#2]
`email = genRandom(28) + '**@gmail.com**' #bisa di ubah
nick = genRandom(6) + 'botbyKIPAS' #bisa di ubah'

@KIPASGTS ...

Bisa @gmail.com diganti pake @yahoo.com?

**Comment by KIPASGTS** [comment]
> `email = genRandom(28) + '**@gmail.com**' #bisa di ubah nick = genRandom(6) + 'botbyKIPAS' #bisa di ubah'
> 
> @KIPASGTS ...
> 
> Bisa @gmail.com diganti pake @yahoo.com?

Bisa

**Comment by ghost** [comment]
Kipas, Applikasi yang digunakan untuk membuat bot apa ya?
@KIPASGTS

**Comment by yuukiconan** [comment]
Pake termux woke
