### ISSUE TITLE
How to do this spam?

### ISSUE THREAD

**Issue by yuukiconan** [KIPASGTS/Brainly-Scrambler#3]
Saya kesulitan cara menjalankan program ini

**Comment by ghost** [comment]
Kipas?

**Comment by ghost** [comment]
mau spam brainly gk?

**Comment by yuukiconan** [comment]
Yup mau

**Comment by yuukiconan** [comment]
Kipas very slow responnya

**Comment by ghost** [comment]
Yuuki mau masuk Ke projext gw gk?

**Comment by ghost** [comment]
gw add dulu

**Comment by yuukiconan** [comment]
Ok

**Comment by ghost** [comment]
dah gw add

**Comment by ghost** [comment]
cek Akunku Bagian project

**Comment by ghost** [comment]
plih project

**Comment by ghost** [comment]
jgn pilih yang Beta

**Comment by ghost** [comment]
kamu habis itu masuk klo bisa lihat collaboratornya Klo ada invited card tekan yes
